/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#201f1f",
        "primary-fixed-dim": "#a4c9ff",
        "primary": "#a4c9ff",
        "tertiary-fixed": "#ffdea4",
        "primary-container": "#60a5fa",
        "secondary-container": "#571bc1",
        "on-tertiary-container": "#4b3500",
        "on-secondary-fixed-variant": "#5516be",
        "error-container": "#93000a",
        "tertiary-container": "#d19900",
        "inverse-primary": "#0060ac",
        "blueprint-line": "rgba(161, 161, 170, 0.05)",
        "surface": "#131313",
        "surface-dim": "#131313",
        "secondary-fixed-dim": "#d0bcff",
        "on-surface": "#e5e2e1",
        "surface-variant": "#353534",
        "zinc-text-secondary": "#A1A1AA",
        "on-tertiary-fixed": "#261900",
        "on-primary-fixed": "#001c39",
        "primary-fixed": "#d4e3ff",
        "on-error": "#690005",
        "on-secondary-fixed": "#23005c",
        "error": "#ffb4ab",
        "secondary-fixed": "#e9ddff",
        "zinc-border": "#27272A",
        "secondary": "#d0bcff",
        "outline": "#8b919d",
        "surface-tint": "#a4c9ff",
        "on-primary-fixed-variant": "#004883",
        "tertiary": "#fabd34",
        "on-tertiary-fixed-variant": "#5d4200",
        "on-primary": "#00315d",
        "on-background": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#fabd34",
        "surface-container-lowest": "#0e0e0e",
        "zinc-text-primary": "#FFFFFF",
        "surface-container-highest": "#353534",
        "background": "#131313",
        "on-secondary": "#3c0091",
        "surface-container-high": "#2a2a2a",
        "surface-bright": "#3a3939",
        "zinc-surface": "#18181B",
        "on-surface-variant": "#c1c7d3",
        "inverse-on-surface": "#313030",
        "surface-container-low": "#1c1b1b",
        "on-secondary-container": "#c4abff",
        "inverse-surface": "#e5e2e1",
        "outline-variant": "#414751",
        "on-primary-container": "#003a6b",
        "on-tertiary": "#412d00"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        unit: "4px",
        "section-gap": "128px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        gutter: "24px",
        "container-max": "1200px"
      },
      fontFamily: {
        "hero-display-mobile": ["Hanken Grotesk"],
        "body-md": ["Inter"],
        "label-mono": ["JetBrains Mono"],
        "headline-lg": ["Hanken Grotesk"],
        "hero-display": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "hero-display-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-mono": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "600" }],
        "hero-display": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
